// Turns the Figma variable exports in /design-tokens into CSS custom properties.
// Run with `npm run tokens` (also runs automatically before `dev` and `build`).
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokensDir = join(root, "design-tokens");
const outFile = join(root, "src/styles/tokens.css");

// Order matters: primitives first, then the tokens that point at them.
// `unit` is what a plain number means in that collection.
// `modes` maps a Figma mode to the media query it applies under (null = default).
const COLLECTIONS = [
  { name: "Colors/base", dir: "Colors_base", prefix: "color" },
  { name: "Sizes/base", dir: "Sizes_base", unit: "px" },
  { name: "Typography/base", dir: "Typography_base", unit: "" },
  { name: "States", dir: "States", prefix: "states", unit: "" },
  { name: "Opacity", dir: "Opacity", prefix: "opacity", unit: "" },
  { name: "Colors", dir: "Colors" },
  {
    name: "Sizes",
    dir: "Sizes",
    unit: "px",
    modes: { Mobile: null, Tablet: "(min-width: 768px)", Desktop: "(min-width: 1024px)" },
  },
  { name: "Components", dir: "Components" },
];

const byName = Object.fromEntries(COLLECTIONS.map((c) => [c.name, c]));

function cssVar(collection, path) {
  const parts = collection.prefix ? [collection.prefix, ...path] : path;
  return (
    "--" +
    parts
      .join("-")
      .replace(/\(.*?\)/g, "")
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/-$/, "")
  );
}

function unitFor(collection, token) {
  if (collection.unit !== undefined) return collection.unit;
  const scopes = token.$extensions?.["com.figma.scopes"] ?? [];
  return scopes.includes("OPACITY") || scopes.includes("FONT_STYLE") ? "" : "px";
}

function literal(token, unit) {
  const v = token.$value;
  if (token.$type === "color") {
    const [r, g, b] = v.components.map((c) => Math.round(c * 255));
    return v.alpha < 1 ? `rgb(${r} ${g} ${b} / ${+v.alpha.toFixed(3)})` : v.hex.toLowerCase();
  }
  if (token.$type === "string") return JSON.stringify(v);
  return `${+Number(v).toFixed(4)}${v === 0 ? "" : unit}`;
}

function value(collection, token) {
  const unit = unitFor(collection, token);
  if (typeof token.$value === "string" && /^\{.+\}$/.test(token.$value)) {
    return `var(${cssVar(collection, token.$value.slice(1, -1).split("."))})`;
  }
  const alias = token.$extensions?.["com.figma.aliasData"];
  const target = alias && byName[alias.targetVariableSetName];
  if (target && token.$type !== "number") {
    return `var(${cssVar(target, alias.targetVariableName.split("/"))})`;
  }
  if (target) {
    const targetToken = { $type: "number", $extensions: {} };
    if (unitFor(target, targetToken) === unit) {
      return `var(${cssVar(target, alias.targetVariableName.split("/"))})`;
    }
  }
  return literal(token, unit);
}

function flatten(node, path = []) {
  const out = [];
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    if (child && typeof child === "object" && "$value" in child) out.push([[...path, key], child]);
    else if (child && typeof child === "object") out.push(...flatten(child, [...path, key]));
  }
  return out;
}

// Media blocks are written in the order the modes are declared, so wider screens win.
const blocks = new Map([[null, []]]);
for (const c of COLLECTIONS) for (const media of Object.values(c.modes ?? {})) if (media) blocks.set(media, []);
for (const collection of COLLECTIONS) {
  const files = readdirSync(join(tokensDir, collection.dir)).filter((f) => f.endsWith(".tokens.json"));
  for (const file of files) {
    const doc = JSON.parse(readFileSync(join(tokensDir, collection.dir, file), "utf8"));
    const mode = doc.$extensions?.["com.figma.modeName"] ?? file.replace(".tokens.json", "");
    const media = collection.modes ? collection.modes[mode] : null;
    if (media === undefined) throw new Error(`No media query set for ${collection.name} mode "${mode}"`);
    if (!blocks.has(media)) blocks.set(media, []);
    const lines = blocks.get(media);
    lines.push(`  /* ${collection.name}${collection.modes ? ` · ${mode}` : ""} */`);
    for (const [path, token] of flatten(doc)) {
      lines.push(`  ${cssVar(collection, path)}: ${value(collection, token)};`);
    }
  }
}

let css = "/* Generated by scripts/build-tokens.mjs from /design-tokens. Do not edit by hand. */\n\n";
for (const [media, lines] of blocks) {
  css += media ? `@media ${media} {\n  :root {\n${lines.map((l) => "  " + l).join("\n")}\n  }\n}\n\n` : `:root {\n${lines.join("\n")}\n}\n\n`;
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, css.trimEnd() + "\n");
console.log(`tokens: wrote ${outFile.replace(root + "/", "")}`);
